### ISSUE TITLE
Update Composer to support later version of Symfony 4.2

### ISSUE THREAD

**Issue by brianwozeniak** [coduo/php-humanizer#110]
Could you update your minimum requirements to allow later version of Symfony. You have these:

```
        "symfony/config": "^2.3|^3.0|^4.0",
        "symfony/translation": "^2.3|^3.0|^4.0",
        "symfony/yaml": "^2.3|^3.0|^4.0",
```

This would allow for those symfony packages from 4.0 up to but not including 4.1 or anything greater. I have other packages that want to use Symfony 4.2. Could you be less restrictive on these, maybe this:

```
        "symfony/config": "^2.3|^3.0|^4",
        "symfony/translation": "^2.3|^3.0|^4",
        "symfony/yaml": "^2.3|^3.0|^4",
```

Then anything 4.x would install, or if you don't want to do that update to support 4.2.x? Thanks!

**Comment by norzechowicz** [comment]
Hey @brianwozeniak I just merged your PR. I'm going to release stable version soon, thanks!
