### ISSUE TITLE
compatibility with symfony 5

### ISSUE THREAD

**Issue by douglasjam** [coduo/php-humanizer#117]
Things are moving forward but this library still restricts the usage with symfony 5, maybe a nice @todo for the future

**Comment by norberttech** [comment]
Hey @douglasjam could you maybe try the latest unreleased version `^4.0@dev` which supports also Symfony 5 and let me know if you are missing anything?

**Comment by douglasjam** [comment]
Yes, 4.0 would be compatible with my current Symfony version, looking forward for this release.
