### ISSUE TITLE
Make installable for L9

### ISSUE THREAD

**Issue by RosiersRobin** [coduo/php-humanizer#128]
Problem 1
    - coduo/php-humanizer[4.0.0, ..., 4.x-dev] require symfony/translation ^4.4|^5.0 -> found symfony/translation[v4.4.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.9 (lock file version) by a partial update and that version does not match. Make sure you list it as an ar
gument for the update command.
    - Root composer.json requires coduo/php-humanizer ^4.0 -> satisfiable by coduo/php-humanizer[4.0.0, 4.0.1, 4.0.2, 4.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require coduo/php-humanizer:*" to figure out if any version is installable, or "composer require coduo/php-humanizer:^2.1" if you know which you need.

**Comment by norberttech** [comment]
Please try now with the latest release `4.0.3`
