### ISSUE TITLE
The Symfony\Polyfill\Intl\Icu\NumberFormatter::__construct() method's argument $style value 0 behavior is not implemented

### ISSUE THREAD

**Issue by maulikinfyom** [coduo/php-humanizer#130]
The Symfony\Polyfill\Intl\Icu\NumberFormatter::__construct() method's argument $style value 0 behavior is not implemented. The available styles are: CURRENCY, DECIMAL.. Please install the "intl" extension for full localization capabilities.

**Comment by norberttech** [comment]
This is expected and pretty much self-descritive behavior, I don't see any issue that could be resolved here. 
Please reach out to symfony intl polyfill authors if you believe this behavior should be covered or do what is proposed in the error (which is better solution if you would ask me) and install the intl extension.
