### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by wturyn** [coduo/php-humanizer#24]
Please add license information.

**Comment by wturyn** [comment]
I've just noticed that there's a MIT button, but it would be nice if you've included license explicitly.

**Comment by Forst** [comment]
There is a full license text available in [/LICENSE](https://github.com/coduo/php-humanizer/blob/master/LICENSE) and it has been there for a couple of years already. I suggest this issue should be closed.

**Comment by norzechowicz** [comment]
@Forst :+1:
