### ISSUE TITLE
String::truncate() support for html text

### ISSUE THREAD

**Issue by Kehet** [coduo/php-humanizer#25]
It would be great if ```String::truncate()``` would also support truncating text with html tags (and not breaking everything with orphan tags) since this is quite common problem in any website which accepts user text content

**Comment by norzechowicz** [comment]
:+1: for that but maybe in different function, like ``String::truncateHtml``

**Comment by smeeckaert** [comment]
I have done it. I will post a PR shortly if everything is okay.

**Comment by norzechowicz** [comment]
@smeeckaert nice!

**Comment by smeeckaert** [comment]
See #30

**Comment by norzechowicz** [comment]
#30 was merged
