### ISSUE TITLE
Any plans for making locales for ordinalize()?

### ISSUE THREAD

**Issue by doenietzomoeilijk** [coduo/php-humanizer#39]
I'd love to be able to add locale rules for ordinals as well, but currently they're hard-coded in English. Any plans / ideas about internationalizing that part as well?

**Comment by defrag** [comment]
That would be nice, we need to dig some test cased first tho, cuz different ordinalize rules applies to different languages.

**Comment by doenietzomoeilijk** [comment]
Absolutely. The test cases would have to be international as well. Since there's more logic involved I don't see the localisation files being doable as Yaml.

Eitherway, I could whip up a couple of test cases for English and Dutch later today, would you like me to do that?

**Comment by norzechowicz** [comment]
@doenietzomoeilijk yes, please : )

**Comment by doenietzomoeilijk** [comment]
Ah, there's already some English-language tests in NumberSpec, of course. I could add Dutch ones but that'd break without an actual implementation, so let's think about that first.

And this is where we have an interesting situation, at least in Dutch... There's two valid ways of specifying an ordinalized number. You can add either an "e", which works for *all* numbers (1e, 2e, 3e, 1000e), _or_ you could go all fancy and use the more irregular version (1ste, 2de, 3de, 1000ste).

 In fact, I'm pretty certain there's more than one way of using ordinals in other languages as well; if I'm not mistaken, in German you can have some letters OR a period, and in French it might even depend on the gender of the word the ordinal has a relation to...  (I looked it up: that's only needed for "first", for the rest you get away with just adding an "e": http://french.about.com/od/vocabulary/a/ordinalnumbers.htm).
Anyway, to add localized ordinal support, you may also have to deal with what comes after the ordinal.

Back to just starting with adding one language: I don't think the Symfony translation interface is useful here, since you need to add actual logic (at least for English, preferrably for other languages as well). I'll think of something, PR it, and then we can take shots at it, OK?
