### ISSUE TITLE
Support for IEC standard prefixes and suffix translation

### ISSUE THREAD

**Issue by zebratrois** [coduo/php-humanizer#63]
I would also being able to use the standard IEC binary prefixes such as "Mi" and "Gi" instead of "M" and "G" in BinarySuffix functions and to use a localized suffix as in french we commonly use "o" instead of "B" (we use "octet(s)" instead of "byte(s)").
I can understand that replacing "GB" by "GiB" by default is counterintuitive as it's not the most commonly used spelling so it could be achieved adding another parameter or usng a "tweaked" locale.
The result could be something like this:

``` php
echo Number::binarySuffix(1073741824 * 2); // "2 GiB"
echo Number::binarySuffix(1073741824 * 2, 'en-iec'); // "2 GiB"
echo Number::binarySuffix(1073741824 * 2, 'fr'); // "2 Go"
echo Number::binarySuffix(1073741824 * 2, 'fr-iec'); // "2 Gio"
```

**Comment by norzechowicz** [comment]
Hi @zebratrois sorry for my late response, I didnt have enough time to take care of this issue. 
Idea sounds cool too me, we can do it adding third parameter into binarySuffix which gonna be 
```php
 NumberHumanizer::binarySuffix(1073741824 * 2, 'fr', false); // "2 Go" last parameter gonna be false by default
 NumberHumanizer::binarySuffix(1073741824 * 2, 'fr', true); // "2 Gio"
```

what do you think about that?

**Comment by zebratrois** [comment]
Hi @norzechowicz, sounds good to me :)

**Comment by norzechowicz** [comment]
are you able to work on that?

**Comment by zebratrois** [comment]
Yes i'll work on that but that'll take some time as i'm unplugging my computer the evening for a 2-weeks vacation ;-)

**Comment by norzechowicz** [comment]
hah sure, have fun!
