### ISSUE TITLE
PHP 7 release

### ISSUE THREAD

**Issue by endihunter** [coduo/php-humanizer#77]
Is there a reason why still not exists 2.0 release? it will allow require this package recursively without downgrading stability settings, thanks.
for ex.: my package A uses your package as a dependency (dev-master). when I try to require my package A with default minimum-stability "stable" it fails and I need to downgrade it up to "@dev".

**Comment by norzechowicz** [comment]
Yes I'm aware of that but currently I dont have enough time to take care of 2.0.0 release. I will do it ASAP.

**Comment by idmontie** [comment]
:+1: @norzechowicz  :cool: Is there any update on this?

**Comment by norzechowicz** [comment]
Sorry for delay : ( I'm going to work that in next few days, I promise :P

**Comment by norzechowicz** [comment]
I just release ``2.0.0-beta`` https://github.com/coduo/php-humanizer/releases/tag/2.0.0-beta - if everything will be fine I will release 2.0.0 as next version in other hand I will first release ``2.0.0-rc``

**Comment by norzechowicz** [comment]
@idmontie its done :) https://github.com/coduo/php-humanizer/releases/tag/2.0.0

**Comment by idmontie** [comment]
:+1: awesome!
