### ISSUE TITLE
Bug: uncaught InvalidArgumentException in CollectionHumanizer::oxford with correct input

### ISSUE THREAD

**Issue by userlond** [coduo/php-humanizer#97]
Test case for  coduo/php-humanizer 2.0.0: 

```php
$collection= [1,2,3];
$limit = 3;
$result = CollectionHumanizer::oxford($collection, $limit, 'ru');
```
The expected result:
`1, 2, 3`

The result I got is exception bellow:
```
[Symfony\Component\Translation\Exception\InvalidArgumentException] 
Unable to choose a translation for &quot;{1} %list% и ещё 1|[2,Inf] %list% и ещё %count%&quot; with locale &quot;ru&quot; for value &quot;0&quot;. Double check that this translation has the correct plural options (e.g. &quot;There is one apple|There are %count% apples&quot;).
```
So if count of items in `$collection` is equal or less than $limit, exception will be throwed.

**Comment by cyrillkalita** [comment]
I am still observing this behavior:

Laravel Framework 10.43.0
coduo/php-humanizer: * 4.0.3
PHP 8.3

using the example above:
```php
$collection= [1,2,3];
$limit = 3;
$result = CollectionHumanizer::oxford($collection, $limit, 'ru');
```

expected: `1,2,3`
throws exception:
` Unable to choose a translation for "{1} %list% и ещё 1|[2,Inf] %list% и ещё %count%" with locale "ru" for value "0". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").`
